import { ArrowRight, ArrowUpRight, Github, Zap, ShieldCheck, SlidersHorizontal, Smartphone, Laptop, Tablet, Command } from 'lucide-react';
import { DecisionDemo } from '../components/decision-demo';
import { Quickstart } from '../components/quickstart';
const repo = 'https://github.com/gtokman/iKev';
export default function Home() {
  return <>
    <header className="site-header container"><a className="brand" href="#" aria-label="iKev home"><span className="brand-symbol">i<span>k</span></span><span>iKev<span className="brand-period">.</span></span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#benchmarks">Benchmarks</a><a href={`${repo}#ikev`} target="_blank" rel="noreferrer">Docs <ArrowUpRight size={12} /></a></nav><a className="github-nav" href={repo} target="_blank" rel="noreferrer"><Github size={17} /><span>Star on GitHub</span><ArrowUpRight size={14} /></a></header>
    <main>
      <section className="hero container"><div className="hero-copy"><div className="release-tag"><span className="live-dot" /> LOCAL INTELLIGENCE. NATIVE SWIFT.<ArrowUpRight size={13} /></div><h1>Small model.<br />Clear <span className="accent-word">decisions<span className="accent-period">.</span></span></h1><p className="hero-description">Not every problem needs a conversation.<br />Run decision models on Apple devices.<br /><span>No generation. No round trips. Just answers.</span></p><div className="hero-actions"><a href="#quickstart" className="button button-primary">Start building <ArrowRight size={17} /></a><a href={repo} className="button button-secondary" target="_blank" rel="noreferrer"><Github size={17} /> View on GitHub</a></div><div className="hero-footnote"><span>Open source</span><span>Swift + MLX</span><span>Built for Apple silicon</span></div></div><DecisionDemo /></section>
      <div className="platform-strip container"><span className="platform-caption">SMALL FOOTPRINT. HOME TURF.</span><div className="platforms"><span><Smartphone size={18} /> iPhone</span><span><Tablet size={20} /> iPad</span><span><Laptop size={22} /> Mac</span></div><span className="platform-end"><Command size={14} /> Powered by MLX</span></div>
      <section className="section container" id="how-it-works"><div className="section-intro"><div><span className="eyebrow">LESS GENERATING. MORE DOING.</span><h2>A decision engine.<br /><span>Not another chatbot.</span></h2></div><p>Give it context and a set of choices. Get calibrated probabilities in a single forward pass. That&apos;s it.</p></div><div className="features"><article><div className="feature-top"><Zap size={22} /><span>01 / FAST</span></div><h3>One pass. One decision.</h3><p>No token-by-token generation. Just a single prefill pass that gets straight to the answer.</p><div className="feature-bottom"><span className="mini-pulse">▂ ▃ ▅ ▇ ▅ ▃ ▂</span><code>prefill → probabilities</code></div></article><article><div className="feature-top"><ShieldCheck size={22} /><span>02 / LOCAL</span></div><h3>Your data stays yours.</h3><p>Runs on Apple silicon, right on the device. After the model downloads, no network is needed.</p><div className="feature-bottom"><span className="live-dot" /><code>on-device by default</code></div></article><article><div className="feature-top"><SlidersHorizontal size={22} /><span>03 / IN CONTROL</span></div><h3>Confidence, not guesswork.</h3><p>Real probabilities. Explicit choices. Set a confidence threshold and decide when to hand off.</p><div className="confidence-mini"><span /><span /><span /><span /><span /><span /><span /><span /><i /><i /><code>0 → 1</code></div></article></div></section>
      <section id="benchmarks" className="benchmarks container"><div className="benchmark-heading"><span className="eyebrow">SMALL MODEL. REAL NUMBERS.</span><span>8-bit checkpoint · Apple M4 Pro</span></div><div className="stats"><div><strong>29<span>ms</span></strong><p>Median decision latency</p></div><div><strong>0.8<span>B</span></strong><p>Backbone parameters</p></div><div><strong>787<span>MB</span></strong><p>Published model size</p></div><div><strong>0</strong><p>Tokens generated</p></div></div><div className="benchmark-note"><span>Measured on Mac. iPhone performance is not yet verified.</span><a href={`${repo}#benchmark`} target="_blank" rel="noreferrer">See methodology <ArrowUpRight size={13} /></a></div></section>
      <div className="container"><Quickstart /></div>
      <section className="closing container"><span className="eyebrow">THE NEXT DECISION IS YOURS.</span><h2>Less cloud.<br className="mobile-only" /> More possibility.</h2><p>Build something that knows what to do next.</p><a className="button button-primary" href={repo} target="_blank" rel="noreferrer">Explore iKev <ArrowUpRight size={17} /></a><span className="status-note">Experimental · Verified on Apple silicon Mac</span></section>
    </main><footer className="container"><a className="brand footer-brand" href="#">iKev<span className="brand-period">.</span></a><span>Small models. Thoughtful software.</span><div><a href="https://github.com/jaredpalmer/kev" target="_blank" rel="noreferrer">Built on Kev <ArrowUpRight size={13} /></a><a href="https://huggingface.co/gtokman/iKev" target="_blank" rel="noreferrer">Model <ArrowUpRight size={13} /></a><a href={repo} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13} /></a></div></footer>
  </>;
}
