'use client';
import { useState } from 'react';
import { Check, Copy, ArrowUpRight } from 'lucide-react';
const snippet = `import Kev\n\nlet model = try await KevModel.load(hubID: "gtokman/iKev")\n\nlet answers = try await model.decide(\n    state: "Set a timer for 10 minutes",\n    questions: [\n        .choice("Which route should handle this message?",\n            options: ["casual", "deviceAction", "assistant"])\n    ]\n)\n\nanswers[0].choice       // "deviceAction"\nanswers[0].confidence   // 0 = uniform, 1 = certain`;
export function Quickstart() {
  const [copyState, setCopyState] = useState('Copy');
  async function copy() { try { await navigator.clipboard.writeText(snippet); setCopyState('Copied'); setTimeout(() => setCopyState('Copy'), 2000); } catch { setCopyState('Select code to copy'); } }
  return <section className="quickstart section" id="quickstart"><div className="section-copy"><span className="eyebrow">NATIVE BY NATURE</span><h2>Feels like Swift.<br /><span>Because it is.</span></h2><p>Add the package. Load a model. Make a decision.<br className="desktop-only" /> No servers to spin up. No API keys to manage.</p><a className="text-link" href="https://github.com/gtokman/iKev#ikev" target="_blank" rel="noreferrer">Read the documentation <ArrowUpRight size={16} /></a><div className="package-tag"><span className="live-dot" /> Swift Package Manager</div></div><div className="code-panel"><div className="code-header"><span><span className="file-dot" /> Decision.swift</span><button onClick={copy}>{copyState === 'Copied' ? <Check size={14} /> : <Copy size={14} />}{copyState}</button></div><pre><code>{snippet.split('\n').map((line, i) => <span className="code-line" key={i}><span className="line-number">{i + 1}</span><span className={line.trim().startsWith('//') ? 'code-comment' : ''}>{line.split(/("[^"]*"|\bimport\b|\blet\b|\btry\b|\bawait\b|\/\/.*)/g).map((part, j) => <span key={j} className={part.startsWith('"') ? 'code-string' : /^(import|let|try|await)$/.test(part) ? 'code-keyword' : part.startsWith('//') ? 'code-comment' : ''}>{part}</span>)}</span></span>)}</code></pre></div></section>;
}
